-- Full NEPSE listed-company directory, seeded from the live NEPSE API.
-- Regenerate with: node scripts/seed-nepse-companies.mjs

create table if not exists public.nepse_companies (
  symbol text primary key,
  company_name text not null,
  sector_name text not null,
  instrument_type text not null default 'Equity',
  status text not null default 'A',
  sort_order integer not null default 0
);

alter table public.nepse_companies enable row level security;

create policy "nepse companies are publicly readable"
  on public.nepse_companies for select
  to public
  using (true);

insert into public.nepse_companies (symbol, company_name, sector_name, instrument_type, status, sort_order) values
('NABIL', 'Nabil Bank Limited', 'Commercial Banks', 'Equity', 'A', 0),
('NIMB', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Equity', 'A', 1),
('SCB', 'Standard Chartered Bank  Nepal Limited', 'Commercial Banks', 'Equity', 'A', 2),
('HBL', 'Himalayan Bank Limited', 'Commercial Banks', 'Equity', 'A', 3),
('SBI', 'Nepal SBI Bank Limited', 'Commercial Banks', 'Equity', 'A', 4),
('NBB', 'Nepal Bangladesh Bank Limited', 'Commercial Banks', 'Equity', 'D', 5),
('EBL', 'Everest Bank Limited', 'Commercial Banks', 'Equity', 'A', 6),
('BOKL', 'Bank of Kathmandu Ltd.', 'Commercial Banks', 'Equity', 'D', 7),
('NICA', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Equity', 'A', 8),
('MBL', 'Machhapuchhre Bank Limited', 'Commercial Banks', 'Equity', 'A', 9),
('LSL', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Equity', 'A', 10),
('KBL', 'Kumari Bank Limited', 'Commercial Banks', 'Equity', 'A', 11),
('LUBL', 'Lumbini Bank Limited', 'Commercial Banks', 'Equity', 'D', 12),
('NCCB', 'Nepal Credit And Commercial Bank Limited', 'Commercial Banks', 'Equity', 'D', 13),
('SBL', 'Siddhartha Bank Limited', 'Commercial Banks', 'Equity', 'A', 14),
('YHL', 'Yak And Yeti Hotel Limited', 'Hotels And Tourism', 'Equity', 'S', 15),
('SHL', 'Soaltee Hotel Limited', 'Hotels And Tourism', 'Equity', 'A', 16),
('TRH', 'Taragaon Regency Hotel Limited', 'Hotels And Tourism', 'Equity', 'A', 17),
('OHL', 'Oriental Hotels Limited', 'Hotels And Tourism', 'Equity', 'A', 18),
('ESC', 'National Pro. And Eco. Dev. Centre', 'Others', 'Equity', 'D', 19),
('NFD', 'Nepal Film Development Company Limited', 'Others', 'Equity', 'S', 20),
('NHPC', 'National Hydro Power Company Limited', 'Hydro Power', 'Equity', 'A', 21),
('BPCL', 'Butwal Power Company Limited', 'Hydro Power', 'Equity', 'A', 22),
('CHCL', 'Chilime Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 23),
('STC', 'Salt Trading Corporation', 'Tradings', 'Equity', 'A', 24),
('BBC', 'Bishal Bazar Company Limited', 'Tradings', 'Equity', 'A', 25),
('NBCK', 'Nepal Byapar Bikash Company(Koshi) Limited', 'Tradings', 'Equity', 'D', 26),
('NTL', 'Nepal Tading Limited', 'Tradings', 'Equity', 'S', 27),
('NWC', 'Nepal Welfare Company Limited', 'Tradings', 'Equity', 'S', 28),
('NIDC', 'NIDC Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 29),
('NDB', 'Nepal Development Bank Limited', 'Development Banks', 'Equity', 'D', 30),
('GRAND', 'Grand Bank Nepal Limited', 'Commercial Banks', 'Equity', 'D', 31),
('NUBL', 'Nirdhan Utthan Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 32),
('CBBL', 'Chhimek Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 33),
('PDBL', 'Paschimanchal Bikash Bank Limited', 'Development Banks', 'Equity', 'D', 34),
('DDBL', 'Deprosc Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 35),
('GDBL1', 'Gandaki Bikas BankLimited', 'Development Banks', 'Equity', 'D', 36),
('BUDBL', 'Business Universal Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 37),
('SDBL', 'Siddhartha Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 38),
('BBBL', 'Bhrikuti Vikash Bank Limited', 'Development Banks', 'Equity', 'D', 39),
('SANIMA', 'Sanima Bank Limited', 'Commercial Banks', 'Equity', 'A', 40),
('NABBC', 'Narayani Development Bank Limited', 'Development Banks', 'Equity', 'A', 41),
('BBBLN', 'Bagheshwori Development Bank Limited', 'Development Banks', 'Equity', 'D', 42),
('SBBLJ', 'Sahayogi Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 43),
('GDBNL', 'Gurkha Development Bank Limited', 'Development Banks', 'Equity', 'D', 44),
('NICL', 'Nepal Insurance Co. Ltd.', 'Non Life Insurance', 'Equity', 'A', 45),
('RBCL', 'Rastriya Beema Company Limited', 'Non Life Insurance', 'Equity', 'A', 46),
('NLICL', 'National Life Insurance Co. Ltd.', 'Life Insurance', 'Equity', 'A', 47),
('HEI', 'Himalayan Everest Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 48),
('UAIL', 'United Ajod Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 49),
('EIC', 'Everest Insurance Co. Ltd.', 'Non Life Insurance', 'Equity', 'D', 50),
('SPIL', 'Siddhartha Premier Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 51),
('NIL', 'Neco Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 52),
('PRIN', 'Prabhu Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 53),
('SALICO', 'Sagarmatha Lumbini Insurance Co. Limited', 'Non Life Insurance', 'Equity', 'A', 54),
('IGI', 'IGI Prudential Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 55),
('NLIC', 'NEPAL LIFE INSURANCE COMPANY LIMITED', 'Life Insurance', 'Equity', 'A', 56),
('LICN', 'Life Insurance Corporation (Nepal) Limited', 'Life Insurance', 'Equity', 'A', 57),
('PICL', 'Prudential Insurance Co. Ltd.', 'Non Life Insurance', 'Equity', 'D', 58),
('LGIL', 'Lumbini General Insurance Co. Ltd.', 'Non Life Insurance', 'Equity', 'D', 59),
('SICL', 'Shikhar Insurance Co. Ltd.', 'Non Life Insurance', 'Equity', 'A', 60),
('MSM', 'Morang Sugar Mills Limited', 'Manufacturing And Processing', 'Equity', 'D', 61),
('NFS', 'Nepal Finance Ltd.', 'Finance', 'Equity', 'A', 62),
('BNL', 'Bottlers Nepal (Balaju) Limited', 'Manufacturing And Processing', 'Equity', 'A', 63),
('NCM', 'NIDC Capital Markets Ltd.', 'Finance', 'Equity', 'D', 64),
('BJM', 'Biratnagar Jute Mills Limited', 'Manufacturing And Processing', 'Equity', 'D', 65),
('NLO', 'Nepal Lube Oil Limited', 'Manufacturing And Processing', 'Equity', 'A', 66),
('NNFC', 'Narayani National Finance Limited', 'Finance', 'Equity', 'D', 67),
('NSM', 'Nepal Share Markets Ltd.', 'Finance', 'Equity', 'S', 68),
('NVG', 'Nepal Vanaspati Ghee Udhyog Limited', 'Manufacturing And Processing', 'Equity', 'S', 69),
('KBBL', 'Kailash Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 70),
('RJM', 'Raghupati Jute Mills Limited', 'Manufacturing And Processing', 'Equity', 'S', 71),
('GUFL', 'Gurkhas Finance Ltd.', 'Finance', 'Equity', 'A', 72),
('BSM', 'Butwal Spinning Mills Limited', 'Manufacturing And Processing', 'Equity', 'S', 73),
('PFCL', 'Peoples Finance Ltd.', 'Finance', 'Equity', 'D', 74),
('GRU', 'Gorakhkali Rubber Udhyog Limited', 'Manufacturing And Processing', 'Equity', 'S', 75),
('UFCL', 'Union Finance Co. Ltd.', 'Finance', 'Equity', 'D', 76),
('JSM', 'Jyoti Sinning Mills Limited', 'Manufacturing And Processing', 'Equity', 'S', 77),
('CIT', 'Citizen Investment Trust', 'Investment', 'Equity', 'A', 78),
('AVU', 'Arun Vanaspati Udhyog Limited', 'Manufacturing And Processing', 'Equity', 'S', 79),
('NABB', 'Nepal Aawas Finance Limited', 'Finance', 'Equity', 'D', 80),
('BNT', 'Bottlers Nepal (Terai) Limited', 'Manufacturing And Processing', 'Equity', 'A', 81),
('NFL', 'Narayani Finance Ltd.', 'Finance', 'Equity', 'D', 82),
('HBT', 'Harisiddhi Brick And Tiles Limited', 'Manufacturing And Processing', 'Equity', 'S', 83),
('ACEDBL', 'Ace Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 84),
('BSL', 'Birat Shoe Limited', 'Manufacturing And Processing', 'Equity', 'S', 85),
('YFL', 'Yeti Finance Ltd.', 'Finance', 'Equity', 'D', 86),
('UNL', 'Unilever Nepal Limited', 'Manufacturing And Processing', 'Equity', 'A', 87),
('GFLK', 'Gorkha Finance Ltd.', 'Finance', 'Equity', 'D', 88),
('SFC', 'Samjhana Finance Co. Ltd.', 'Finance', 'Equity', 'S', 89),
('NKU', 'Nepal Khadya Udhyog Limited', 'Manufacturing And Processing', 'Equity', 'S', 90),
('UFLK', 'Universal Finance Ltd.', 'Finance', 'Equity', 'D', 91),
('HTL', 'Himgiri Textile Industries Limited', 'Manufacturing And Processing', 'Equity', 'D', 92),
('NHMF', 'Nepal Housing & Merchant Finance Ltd.', 'Finance', 'Equity', 'D', 93),
('SBPP', 'Shree Bhrikuti Pulp And Paper Limited', 'Manufacturing And Processing', 'Equity', 'S', 94),
('BFC', 'Best Finance Company Ltd.', 'Finance', 'Equity', 'A', 95),
('FHL', 'Fleur Himalayan Limited', 'Manufacturing And Processing', 'Equity', 'S', 96),
('MFL', 'Maha Laxmi Finance Ltd.', 'Finance', 'Equity', 'D', 97),
('SRS', 'Shree Ram Sugar Mills Limited', 'Manufacturing And Processing', 'Equity', 'S', 98),
('LFC', 'Lalitpur Finance Ltd.', 'Finance', 'Equity', 'D', 99),
('GFCL', 'Goodwill Finance Limited', 'Finance', 'Equity', 'A', 100),
('NBBU', 'Nepal Bitumin And Barrel Udhyog Limited', 'Manufacturing And Processing', 'Equity', 'S', 101),
('PFC', 'Paschimanchal Finance Co. Ltd.', 'Finance', 'Equity', 'D', 102),
('HDL', 'Himalayan Distillery Limited', 'Manufacturing And Processing', 'Equity', 'A', 103),
('PFL', 'Pokhara Finance Ltd.', 'Finance', 'Equity', 'A', 104),
('LFLC', 'Lumbini Finance Ltd.', 'Finance', 'Equity', 'D', 105),
('NMB', 'NMB Bank Limited', 'Commercial Banks', 'Equity', 'A', 106),
('SFL', 'Siddharth Finance Ltd.', 'Finance', 'Equity', 'D', 107),
('AEFL', 'Alpic Everest Finance Co. Ltd.', 'Finance', 'Equity', 'D', 108),
('NBFL', 'Nepal Bangladesh Finance & Leasing Co. Ltd.', 'Finance', 'Equity', 'D', 109),
('UFL', 'United Finance Ltd.', 'Finance', 'Equity', 'D', 110),
('ILFC', 'International Leasing & Finance Co. Ltd.', 'Finance', 'Equity', 'D', 111),
('SIFC', 'Shree Investment Finance Co. Ltd.', 'Finance', 'Equity', 'A', 112),
('CFCL', 'Central Finance Co. Ltd.', 'Finance', 'Equity', 'A', 113),
('NSLMB', 'Nepal Shree Lanka Merchant Banking & Finance Ltd', 'Finance', 'Equity', 'D', 114),
('PFCLL', 'Premier Finance Co. Ltd.', 'Finance', 'Equity', 'D', 115),
('NDFL', 'Nava Durga Finance Co. Ltd.', 'Finance', 'Equity', 'D', 116),
('SYFL', 'Synergy Finance Ltd.', 'Finance', 'Equity', 'D', 117),
('JFL', 'Janaki Finance Company Limited', 'Finance', 'Equity', 'A', 118),
('STFL', 'Standard Finance Ltd.', 'Finance', 'Equity', 'D', 119),
('OFL', 'Om Finance Ltd.', 'Finance', 'Equity', 'D', 120),
('CMBF', 'CMB Finance Limited', 'Finance', 'Equity', 'D', 121),
('FFCL', 'Fewa Finance Co. Ltd.', 'Finance', 'Equity', 'D', 122),
('PRVU', 'Prabhu  Bank Limited', 'Commercial Banks', 'Equity', 'A', 123),
('SFCL', 'Samriddhi Finance Company Limited', 'Finance', 'Equity', 'D', 124),
('BJFL', 'Birgunj Finance Ltd.', 'Finance', 'Equity', 'D', 125),
('EFL', 'Everest Finance Ltd.', 'Finance', 'Equity', 'D', 126),
('CMB', 'Capital Merchant Bank & Finance Co. Ltd.', 'Finance', 'Equity', 'S', 127),
('PFIL', 'Prudential Finance Company Limited', 'Finance', 'Equity', 'D', 128),
('SFFIL', 'Shrijana Finance  (Bittaya Sanstha)', 'Finance', 'Equity', 'D', 129),
('APEX', 'Apex Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 130),
('GMFIL', 'Guheswori Merchant Banking & Finance Ltd.', 'Finance', 'Equity', 'A', 131),
('IMEFI', 'IME Financial Institution', 'Finance', 'Equity', 'D', 132),
('BFIL', 'Bhajuratna Finance & Saving Co. Ltd.', 'Finance', 'Equity', 'D', 133),
('PFLBS', 'Patan Finance Limited', 'Finance', 'Equity', 'D', 134),
('SUPRME', 'Supreme Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 135),
('SWBBL', 'Swabalamban Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 136),
('NCMMF', 'NIDC Capital Markets Ltd.', 'Finance', 'Mutual Funds', 'D', 137),
('IFIL', 'Imperial Financial Inst. Ltd.', 'Finance', 'Equity', 'D', 138),
('SODBL', 'Society Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 139),
('CMBSL', 'Civil Merchant Bittiya Santha Ltd.', 'Finance', 'Equity', 'D', 140),
('ICFC', 'ICFC Finance Limited', 'Finance', 'Equity', 'A', 141),
('EDBL', 'Excel Development Bank Ltd.', 'Development Banks', 'Equity', 'A', 142),
('MLBL1', 'Mahalaxmi BikasBank Limited', 'Development Banks', 'Equity', 'D', 143),
('EBLCP', 'Everest Bank Limited', 'Commercial Banks', 'Preference Shares', 'D', 144),
('NEFL', 'Nepal Express Finance Ltd.', 'Finance', 'Equity', 'D', 145),
('BLDBL', 'Biratlaxmi Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 146),
('SIL', 'Siddhartha Insurance Ltd.', 'Non Life Insurance', 'Equity', 'D', 147),
('IDBL', 'Infrastructure Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 148),
('CEFL', 'City Express Finance Co. Limited', 'Finance', 'Equity', 'D', 149),
('NTC', 'Nepal Doorsanchar Company Limited', 'Others', 'Equity', 'A', 150),
('PRBBL', 'Prabhu Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 151),
('DBBL', 'Deva Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 152),
('LBFIL', 'Lord Buddha Finance Limited', 'Finance', 'Equity', 'D', 153),
('SAFL', 'Sagarmatha  Finance Limited', 'Finance', 'Equity', 'D', 154),
('SUBBL', 'Subhechha Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 155),
('KAFIL', 'Kaski Finance Limited', 'Finance', 'Equity', 'D', 156),
('CEDBL', 'Clean Energy Development Bank Limited', 'Development Banks', 'Equity', 'D', 157),
('TBBL', 'Triveni Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 158),
('PROFL', 'Progressive Finance Limited', 'Finance', 'Equity', 'A', 159),
('PGBL', 'Purwanchal Grameen Bikash Bank Limited', 'Development Banks', 'Equity', 'D', 160),
('GBIME', 'Global IME Bank Limited', 'Commercial Banks', 'Equity', 'A', 161),
('REDBL', 'Reliable Development Bank Limited', 'Development Banks', 'Equity', 'D', 162),
('AXIS', 'Axis Development Bank Limited', 'Development Banks', 'Equity', 'D', 163),
('SBSL', 'Shikhar Finance Limited', 'Finance', 'Equity', 'D', 164),
('CZBIL', 'Citizens Bank International Limited', 'Commercial Banks', 'Equity', 'A', 165),
('BOAN', 'Bank of Asia Nepal Limited', 'Commercial Banks', 'Equity', 'D', 166),
('AFL', 'Api Finance Limited', 'Finance', 'Equity', 'D', 167),
('PCBL', 'Prime Commercial Bank Ltd.', 'Commercial Banks', 'Equity', 'A', 168),
('LBBL', 'Lumbini Bikas Bank Ltd.', 'Development Banks', 'Equity', 'A', 169),
('SRBL', 'Sunrise Bank Limited', 'Commercial Banks', 'Equity', 'D', 170),
('AHPC', 'Arun Valley Hydropower Development Company Limited', 'Hydro Power', 'Equity', 'A', 171),
('CFL', 'Crystal Finance Ltd.', 'Finance', 'Equity', 'S', 172),
('MGBL', 'Madhyamanchal Gramin Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 173),
('PDB', 'Public Development Bank Limited', 'Development Banks', 'Equity', 'D', 174),
('MBBL', 'Mahakali Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 175),
('MDB', 'Miteri Development Bank Limited', 'Development Banks', 'Equity', 'A', 176),
('PBSL', 'Pathibhara Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 177),
('RBSL', 'Resunga Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 178),
('ALICL', 'Asian Life Insurance Co Limited', 'Life Insurance', 'Equity', 'A', 179),
('KDBL', 'Kasthamandap Development Bank Limited', 'Development Banks', 'Equity', 'D', 180),
('SEWA', 'Sewa Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 181),
('HLI', 'Himalayan Life Insurance Limited', 'Life Insurance', 'Equity', 'A', 182),
('NGBL', 'Nilgiri Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 183),
('NMLBBL', 'Nerude Mirmire Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 184),
('ADBL', 'Agricultural Development Bank Limited', 'Commercial Banks', 'Equity', 'A', 185),
('ODBL', 'Om Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 186),
('MLBL', 'Mahalaxmi Bikas Bank Ltd.', 'Development Banks', 'Equity', 'A', 187),
('SJLIC', 'SuryaJyoti Life Insurance Company Limited', 'Life Insurance', 'Equity', 'A', 188),
('UBBL', 'Udhyam Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 189),
('ALDBL', 'Alpine Development Bank Limited', 'Development Banks', 'Equity', 'D', 190),
('SDFL', 'Suryadarshan Finance Company Limited', 'Finance', 'Equity', 'D', 191),
('ZFL', 'Zenith Finance Limited', 'Finance', 'Equity', 'D', 192),
('SMF', 'Swastik Merchant Finance Co. Ltd.', 'Finance', 'Equity', 'D', 193),
('SLFL', 'Subha Laxmi Finance Co. Ltd.', 'Finance', 'Equity', 'D', 194),
('GSDBL', 'Gaurishankar Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 195),
('UFIL', 'Unique Finance Ltd.', 'Finance', 'Equity', 'D', 196),
('PRDBL', 'Professional Diyalo Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 197),
('SETI', 'Seti Finance Limited', 'Finance', 'Equity', 'D', 198),
('GBBL', 'Garima Bikas Bank Limited', 'Development Banks', 'Equity', 'A', 199),
('JBBL', 'Jyoti Bikas Bank Limited', 'Development Banks', 'Equity', 'A', 200),
('KNBL', 'Kankai Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 201),
('GDBL', 'Gandaki Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 202),
('HATH', 'Hathway Finance Company Limited', 'Finance', 'Equity', 'D', 203),
('KEBL', 'Kabeli Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 204),
('KRBL', 'Karnali Development Bank Limited', 'Development Banks', 'Equity', 'S', 205),
('HFL', 'Himalayan Finance Limited (Bittiya Sanstha)', 'Finance', 'Equity', 'S', 206),
('TNBL', 'Tinau Development Bank Limited', 'Development Banks', 'Equity', 'D', 207),
('ARDBL', 'Araniko Development Bank Limited', 'Development Banks', 'Equity', 'D', 208),
('VFL', 'Valley Finance Limited', 'Finance', 'Equity', 'D', 209),
('WDBL', 'Western Development Bank Limited', 'Development Banks', 'Equity', 'D', 210),
('PRBL', 'Professional Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 211),
('GLICL', 'Gurans Life Insurance Company Ltd.', 'Life Insurance', 'Equity', 'D', 212),
('CNDBL', 'Country Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 213),
('CORBL', 'Corporate Development Bank Limited', 'Development Banks', 'Equity', 'A', 214),
('PURBL', 'Purnima Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 215),
('KSBBL', 'Kamana Sewa Bikas Bank Limited', 'Development Banks', 'Equity', 'A', 216),
('RARA', 'Rara Bikas Bank Limited', 'Development Banks', 'Equity', 'D', 217),
('HAMA', 'Hama Merchant & Finance Ltd.', 'Finance', 'Equity', 'D', 218),
('MPFL', 'Multipurpose Finance Company  Limited', 'Finance', 'Equity', 'A', 219),
('SADBL', 'SHANGRI-LA DEVELOPMENT BANK LIMITED', 'Development Banks', 'Equity', 'A', 220),
('SHINE', 'SHINE RESUNGA DEVELOPMENT BANK LTD', 'Development Banks', 'Equity', 'A', 221),
('MNBBL', 'Muktinath Bikas Bank Ltd.', 'Development Banks', 'Equity', 'A', 222),
('BHBL', 'Bhargav Bikash Bank Ltd.', 'Development Banks', 'Equity', 'D', 223),
('BGDBL', 'Bagmati Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 224),
('FMDBL', 'First Micro Finance Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 225),
('JBNL', 'Janata Bank Nepal Ltd.', 'Commercial Banks', 'Equity', 'D', 226),
('SMFDB', 'Summit Micro Finance Development Bank Ltd.', 'Microfinance', 'Equity', 'D', 227),
('TDBL', 'Tourism Development Bank Limited', 'Development Banks', 'Equity', 'D', 228),
('GULMI', 'Gulmi Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 229),
('KADBL', 'Kanchan Development Bank Limited', 'Development Banks', 'Equity', 'D', 230),
('NCDBL', 'Nepal Consumer Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 231),
('PADBL', 'Pacific Development Bank Limited', 'Development Banks', 'Equity', 'D', 232),
('METRO', 'Metro Development Bank Limited', 'Development Banks', 'Equity', 'D', 233),
('RDBL', 'Rising Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 234),
('MFIL', 'Manjushree Finance Ltd.', 'Finance', 'Equity', 'A', 235),
('NBL', 'Nepal Bank Limited', 'Commercial Banks', 'Equity', 'A', 236),
('SIGS1', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 237),
('INDB', 'Innovative Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 238),
('KKBL', 'Kakre Bihar Bikash Bank Ltd', 'Development Banks', 'Equity', 'D', 239),
('CBL', 'Civil Bank Ltd', 'Commercial Banks', 'Equity', 'D', 240),
('CIVIC', 'Civic Development Bank Ltd', 'Development Banks', 'Equity', 'D', 241),
('BRTBL', 'Bright Development Bank Ltd', 'Development Banks', 'Equity', 'D', 242),
('INDBL', 'International Development Bank Ltd', 'Development Banks', 'Equity', 'D', 243),
('KHDBL', 'Khandbari Development Bank Ltd', 'Development Banks', 'Equity', 'D', 244),
('NBF1', 'Nabil Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 245),
('CTBNL', 'Commerz and Trust Bank Nepal Ltd.', 'Commercial Banks', 'Equity', 'D', 246),
('SLBBL', 'Swarojgar Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 247),
('NLG', 'NLG Insurance Company Ltd.', 'Non Life Insurance', 'Equity', 'A', 248),
('SINDU', 'Sindhu Bikash Bank Ltd', 'Development Banks', 'Equity', 'A', 249),
('MEGA', 'Mega  Bank Nepal Ltd.', 'Commercial Banks', 'Equity', 'D', 250),
('JHBL', 'Jhimruk Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 251),
('MIDBL', 'Mission Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 252),
('NBSL', 'Namaste Bittiya Sanstha Ltd.', 'Finance', 'Equity', 'D', 253),
('GABL', 'Gaumukhee Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 254),
('SKBBL', 'Sana Kisan Bikas Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 255),
('RMDC', 'RMDC Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 256),
('HAMRO', 'Hamro Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 257),
('JEFL', 'Jebils Finance Ltd.', 'Finance', 'Equity', 'D', 258),
('GBLBS', 'Grameen Bikas Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 259),
('RLFL', 'Reliance Finance Ltd.', 'Finance', 'Equity', 'A', 260),
('MSBBL', 'Manaslu Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 261),
('SHPC', 'Sanima Mai Hydropower Limited', 'Hydro Power', 'Equity', 'A', 262),
('NSLB', 'Naya Sarathi Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 263),
('KMCDB', 'Kalika Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 264),
('MTBL', 'Matribhumi Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 265),
('NCDB', 'Nepal Community Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 266),
('CSDBL', 'Cosmos Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 267),
('MLBBL', 'Mithila LaghuBitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 268),
('NBBL', 'NagBeli LaghuBitta Bikas Bank Ltd.', 'Microfinance', 'Equity', 'D', 269),
('CCBL', 'Century Commercial Bank Ltd.', 'Commercial Banks', 'Equity', 'D', 270),
('TRHPR', 'Taragaon Regency Hotel Limited', 'Hotels And Tourism', 'Preference Shares', 'D', 271),
('RIDI', 'Ridi Power Company Limited', 'Hydro Power', 'Equity', 'A', 272),
('MMDBL', 'Mount Makalu Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 273),
('SEOS', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 274),
('EKBL', 'Ekata Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 275),
('LLBS', 'Laxmi Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 276),
('SHBL', 'Sahara Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 277),
('KCDBL', 'Kalinchowk Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 278),
('NMBSF1', 'NMB Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 279),
('NIBSF1', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 280),
('LVF1', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 281),
('RBBBL', 'Raptibheri Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 282),
('BFCL', 'Bhaktapur Finance Co. Ltd.', 'Finance', 'Equity', 'D', 283),
('MMFDB', 'Mirmire Laghubitta Bittya Sanstha Limited', 'Microfinance', 'Equity', 'D', 284),
('BARUN', 'Barun Hydropower Co. Ltd.', 'Hydro Power', 'Equity', 'A', 285),
('VLBS', 'Vijaya laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 286),
('MSMBS', 'Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 287),
('SBLD78', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 288),
('HLBSL', 'Himalayan Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 289),
('MATRI', 'Matribhumi Lagubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 290),
('JSLBB', 'Janautthan Samudayic Laghubitta Bittya Sanstha Limited', 'Microfinance', 'Equity', 'A', 291),
('API', 'API POWER COMPANY LIMITED', 'Hydro Power', 'Equity', 'A', 292),
('NMBMF', 'NMB  Microfinance Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 293),
('GILB', 'Global IME Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 294),
('SWMF', 'Suryodaya Womi Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 295),
('SKDBL', 'Saptakoshi Development Bank Ltd.', 'Development Banks', 'Equity', 'D', 296),
('SAJHA', 'Sajha Bikas Bank Ltd.', 'Development Banks', 'Equity', 'D', 297),
('GIMES1', 'Global IME Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 298),
('MERO', 'Meromicrofinance Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 299),
('HIDCL', 'Hydorelectricity Investment and Development Company Ltd', 'Investment', 'Equity', 'A', 300),
('NGPL', 'Ngadi Group Power Ltd.', 'Hydro Power', 'Equity', 'A', 301),
('GRDBL', 'Green Development Bank Ltd.', 'Development Banks', 'Equity', 'A', 302),
('NMFBS', 'National  Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 303),
('RSDC', 'RSDC Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 304),
('SLBS', 'Suryodaya Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 305),
('KKHC', 'Khanikhola Hydropower Co. Ltd.', 'Hydro Power', 'Equity', 'A', 306),
('NMBHF1', 'NMB Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 307),
('NEF', 'Nabil Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 308),
('DHPL', 'Dibyashwori Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 309),
('NIBLPF', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 310),
('AKPL', 'Arun Kabeli Power Ltd.', 'Hydro Power', 'Equity', 'A', 311),
('FOWAD', 'Forward Microfinance Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 312),
('SPDL', 'Synergy Power Development Ltd.', 'Hydro Power', 'Equity', 'A', 313),
('UMHL', 'United Modi Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 314),
('SMATA', 'Samata Gharelu Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 315),
('SDESI', 'Swadeshi Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 316),
('LEMF', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 317),
('CHL', 'Chhyangdi Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 318),
('HPPL', 'Himalayan Power Partner Ltd.', 'Hydro Power', 'Equity', 'A', 319),
('MSLB', 'Mahuli Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 320),
('NHDL', 'Nepal Hydro Developers Ltd', 'Hydro Power', 'Equity', 'A', 321),
('SEF', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 322),
('SMB', 'Support Lagubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 323),
('SAEF', 'Sanima Bank Limited', 'Commercial Banks', 'Mutual Funds', 'D', 324),
('USLB', 'Unnati Sahakarya Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 325),
('RADHI', 'Radhi Bidyut Company Ltd', 'Hydro Power', 'Equity', 'A', 326),
('AMFI', 'Arambha Microfinance Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 327),
('NICGF', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Mutual Funds', 'D', 328),
('CMF1', 'Citizens Bank International Limited', 'Commercial Banks', 'Mutual Funds', 'D', 329),
('WNLB', 'Wean Nepal Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'S', 330),
('RRHP', 'Rairang Hydropower Development Company Ltd.', 'Hydro Power', 'Equity', 'D', 331),
('NADEP', 'Nadep Laghubittiya bittya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 332),
('PMHPL', 'Panchakanya Mai Hydropower Ltd', 'Hydro Power', 'Equity', 'A', 333),
('KPCL', 'Kalika power Company Ltd', 'Hydro Power', 'Equity', 'A', 334),
('AKJCL', 'Ankhu Khola Jalvidhyut Company Limited', 'Hydro Power', 'Equity', 'A', 335),
('JOSHI', 'Joshi Hydropower Development Company Ltd', 'Hydro Power', 'Equity', 'A', 336),
('ACLBSL', 'Aarambha Chautari Laghubitta Bittya Sanstha Limited', 'Microfinance', 'Equity', 'A', 337),
('UPPER', 'Upper Tamakoshi Hydropower Ltd', 'Hydro Power', 'Equity', 'A', 338),
('SLBSL', 'Samudayik Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 339),
('GHL', 'Ghalemdi Hydro Limited', 'Hydro Power', 'Equity', 'A', 340),
('ALBSL', 'Asha Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'A', 341),
('SHIVM', 'Shivam Cements Limited', 'Manufacturing And Processing', 'Equity', 'A', 342),
('UPCL', 'Universal Power Company Limited', 'Hydro Power', 'Equity', 'A', 343),
('MHNL', 'Mountain Hydro Nepal Limited', 'Hydro Power', 'Equity', 'A', 344),
('SPARS', 'Sparsha Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 345),
('PPCL', 'Panchthar Power Company Ltd', 'Hydro Power', 'Equity', 'A', 346),
('GMFBS', 'Ganapati Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 347),
('NAGRO', 'Nepal Agro Laghubitta Bittiya Sanstha Ltd.', 'Microfinance', 'Equity', 'D', 348),
('HURJA', 'Himalaya Urja Bikas Company Limited', 'Hydro Power', 'Equity', 'A', 349),
('NICAD85/86', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 350),
('GLBSL', 'Gurans Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 351),
('SAND2085', 'Sanima Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 352),
('SMFBS', 'Swabhumaan Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 353),
('UNHPL', 'Union Hydropower Limited', 'Hydro Power', 'Equity', 'A', 354),
('ILBS', 'Infinity Laghubitta Bittiya Sastha Ltd', 'Microfinance', 'Equity', 'A', 355),
('SRD80', 'Sunrise Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 356),
('NBF2', 'Nabil Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 357),
('GBD80/81', 'Global IME Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 358),
('RHPL', 'Rasuwagadhi Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 359),
('SJCL', 'SANJEN JALAVIDHYUT COMPANY LTD', 'Hydro Power', 'Equity', 'A', 360),
('SABSL', 'Sabaiko Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 361),
('AKBSL', 'Adhikhola Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 362),
('NMBD2085', 'NMB Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 363),
('NIBD2082', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 364),
('GGBSL', 'ghodighoda laghubitta bittiya sanstha ltd', 'Microfinance', 'Equity', 'D', 365),
('NBBD2085', 'Nepal Bangladesh Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 366),
('TMDBL', 'Tinau Mission Development Bank Ltd', 'Development Banks', 'Equity', 'D', 367),
('SIGS2', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 368),
('SAPDBL', 'Saptakoshi Development bank Ltd', 'Development Banks', 'Equity', 'A', 369),
('CMF2', 'CBIL Capital Limited', 'Mutual Fund', 'Mutual Funds', 'D', 370),
('NICBF', 'NIC ASIA Capital Ltd', 'Mutual Fund', 'Mutual Funds', 'A', 371),
('SBLD83', 'Siddhartha Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 372),
('MBLD2085', 'Machhapuchhre Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 373),
('NMB50', 'NMB Capital Ltd.', 'Mutual Fund', 'Mutual Funds', 'D', 374),
('NICD83/84', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 375),
('NICAD8283', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 376),
('BOKD2079', 'Bank of Kathmandu Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 377),
('EBLD2078', 'Everest Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 378),
('SBLD2082', 'Siddhartha Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 379),
('HBLD83', 'Himalayan Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 380),
('PBLD86', 'Prabhu  Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 381),
('SFMF', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 382),
('SRBLD83', 'Sunrise Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 383),
('LBLD86', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 384),
('HDHPC', 'Himal Dolakha Hydropower Com. Ltd.', 'Hydro Power', 'Equity', 'A', 385),
('NRIC', 'Nepal Reinsurance Company Limited', 'Others', 'Equity', 'A', 386),
('ICFCD83', 'ICFC Finance Limited', 'Finance', 'Non-Convertible Debentures', 'A', 387),
('GWFD83', 'Goodwill Finance Limited', 'Finance', 'Non-Convertible Debentures', 'A', 388),
('KBLD86', 'Kumari Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 389),
('ADBLD83', 'Agricultural Development Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 390),
('NICLBSL', 'NIC ASIA Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 391),
('CIZBD86', 'Citizens Bank International Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 392),
('SBIBD86', 'Nepal SBI Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 393),
('NBLD82', 'Nabil Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 394),
('AIL', 'Ajod Insurance Ltd', 'Non Life Insurance', 'Equity', 'D', 395),
('NICAD8182', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'D', 396),
('SMPDA', 'Sampada Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 397),
('NRN', 'NRN Infrastructure and Development Limited', 'Investment', 'Equity', 'A', 398),
('RLI', 'Reliance Life Insurance Limited', 'Life Insurance', 'Equity', 'D', 399),
('LUK', 'Laxmi Capital Market Limited', 'Mutual Fund', 'Mutual Funds', 'A', 400),
('LEC', 'Liberty Energy Company Limited', 'Hydro Power', 'Equity', 'A', 401),
('PBLD84', 'Prabhu  Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 402),
('GIC', 'General Insurance Company Nepal Ltd', 'Non Life Insurance', 'Equity', 'D', 403),
('SSHL', 'Shiva Shree Hydropower Limited', 'Hydro Power', 'Equity', 'A', 404),
('SGIC', 'Sanima GIC Insurance Limited', 'Non Life Insurance', 'Equity', 'A', 405),
('SBLD84', 'Siddhartha Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 406),
('MEN', 'Mountain Energy Nepal Limited', 'Hydro Power', 'Equity', 'A', 407),
('UMRH', 'United Idi Mardi & RB Hydropower Ltd', 'Hydro Power', 'Equity', 'A', 408),
('PMLI', 'Prabhu Mahalaxmi Life Insurance Limited', 'Life Insurance', 'Equity', 'A', 409),
('CGH', 'Chandragiri Hills Limited', 'Hotels And Tourism', 'Equity', 'A', 410),
('NIFRA', 'Nepal Infrastructure Bank Limited', 'Investment', 'Equity', 'A', 411),
('SBD87', 'Sanima Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 412),
('SLCF', 'Sanima Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 413),
('GLH', 'Greenlife Hydropower Limited', 'Hydro Power', 'Equity', 'A', 414),
('MLBSL', 'Mahila Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 415),
('JLI', 'Jyoti Life Insurance Company Limited', 'Life Insurance', 'Equity', 'D', 416),
('NIBD84', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 417),
('MFLD85', 'Manjushree Finance Ltd.', 'Finance', 'Non-Convertible Debentures', 'A', 418),
('KEF', 'Kumari Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 419),
('SHEL', 'Singati Hydro Energy Ltd', 'Hydro Power', 'Equity', 'A', 420),
('RURU', 'Ru Ru Jalbidhyut  Pariyojana Ltd.', 'Hydro Power', 'Equity', 'A', 421),
('NCCD86', 'Nepal Credit And Commercial Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 422),
('SBCF', 'Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 423),
('CHDC', 'CEDB Hydropower Development Company Limited', 'Investment', 'Equity', 'A', 424),
('PSF', 'Prabhu  Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 425),
('KSBBLD87', 'Kamana Sewa Bikas Bank Limited', 'Development Banks', 'Non-Convertible Debentures', 'A', 426),
('NIBSF2', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 427),
('JBLB', 'Jeevan Bikas Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'A', 428),
('MKLB', 'Manakamana Smart Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 429),
('ULI', 'UnionLife Insurance Co. Ltd.', 'Life Insurance', 'Equity', 'D', 430),
('NBLD87', 'Nepal Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 431),
('ADBLB', 'Agricultural Development Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 432),
('BOKD86', 'Bank of Kathmandu Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 433),
('PBLD87', 'Prabhu  Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 434),
('NMBD87/88', 'NMB Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 435),
('NMBEB92/93', 'NMB Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 436),
('SAMAJ', 'Samaj Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'D', 437),
('NICSF', 'NIC ASIA Capital Ltd', 'Mutual Fund', 'Mutual Funds', 'A', 438),
('RMF1', 'RBB Merchant Banking Limited', 'Mutual Fund', 'Mutual Funds', 'A', 439),
('MND84/85', 'Muktinath Bikas Bank Ltd.', 'Development Banks', 'Non-Convertible Debentures', 'A', 440),
('SRLI', 'Sanima Reliance Life Insurance Limited', 'Life Insurance', 'Equity', 'A', 441),
('LBLD88', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 442),
('PBD85', 'Prime Commercial Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 443),
('SDBD87', 'SHANGRI-LA DEVELOPMENT BANK LIMITED', 'Development Banks', 'Non-Convertible Debentures', 'A', 444),
('MBLD87', 'Machhapuchhre Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 445),
('NICD88', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 446),
('RBBD83', 'Rastriya Banijya Bank', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 447),
('GBILD86/87', 'Global IME Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 448),
('MKJC', 'Mailung Khola Jal Vidhyut Company Limited', 'Hydro Power', 'Equity', 'A', 449),
('MLBS', 'Manushi Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 450),
('JBBD87', 'Jyoti Bikas Bank Limited', 'Development Banks', 'Non-Convertible Debentures', 'A', 451),
('SAHAS', 'Sahas Urja Limited', 'Hydro Power', 'Equity', 'A', 452),
('TPC', 'Terhathum Power Company Limited', 'Hydro Power', 'Equity', 'A', 453),
('MMF1', 'Mega  Bank Nepal Ltd.', 'Commercial Banks', 'Mutual Funds', 'A', 454),
('NBF3', 'Nabil Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 455),
('SPC', 'Samling power company limited', 'Hydro Power', 'Equity', 'A', 456),
('NYADI', 'Nyadi hydropower limited', 'Hydro Power', 'Equity', 'A', 457),
('NBLD85', 'Nabil Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 458),
('ADBLB86', 'Agricultural Development Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 459),
('ADBLB87', 'Agricultural Development Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 460),
('MBJC', 'Madhya Bhotekoshi Jalavidyut Company Limited', 'Hydro Power', 'Equity', 'A', 461),
('BNHC', 'Buddha bhumi nepal hydro power company limited', 'Hydro Power', 'Equity', 'A', 462),
('GBBD85', 'Garima Bikas Bank Limited', 'Development Banks', 'Non-Convertible Debentures', 'A', 463),
('ENL', 'Emerging nepal limited', 'Investment', 'Equity', 'A', 464),
('RULB', 'Rastra Utthan Laghubitta Sanstha Limited', 'Microfinance', 'Equity', 'D', 465),
('JALPA', 'Jalpa Samudayik Laghubitta Sanstha Limited', 'Microfinance', 'Equity', 'D', 466),
('NESDO', 'NESDO Sambridha Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 467),
('CBLD88', 'Civil Bank Ltd', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 468),
('EBLD86', 'Everest Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 469),
('GVL', 'Green Ventures Limited', 'Hydro Power', 'Equity', 'A', 470),
('BHL', 'Balephi Hydropower Limited', 'Hydro Power', 'Equity', 'A', 471),
('ULBSL', 'Upakar Laghubitta Bittiya  Sanstha  Limited', 'Microfinance', 'Equity', 'A', 472),
('CYCL', 'CYC Nepal laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 473),
('RFPL', 'River Falls power Limited', 'Hydro Power', 'Equity', 'A', 474),
('CCBD88', 'Century Commercial Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 475),
('DORDI', 'Dordi Khola Jal Bidyut Company limited', 'Hydro Power', 'Equity', 'A', 476),
('ADLB', 'Adarsha Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'D', 477),
('NICFC', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Mutual Funds', 'A', 478),
('KDBY', 'Kumari Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 479),
('BHDC', 'Bindhyabasini Hydropower Development Company Limited', 'Hydro Power', 'Equity', 'A', 480),
('HHL', 'Himalayan Hydropower Limited', 'Hydro Power', 'Equity', 'A', 481),
('PBD88', 'Prime Commercial Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 482),
('SBLD89', 'Siddhartha Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 483),
('UHEWA', 'Upper Hewakhola Hydropower company Limited', 'Hydro Power', 'Equity', 'A', 484),
('SGHC', 'Swet-Ganga Hydropower and Construction Limited', 'Hydro Power', 'Equity', 'A', 485),
('MHL', 'Mandakini Hydropower Limited', 'Hydro Power', 'Equity', 'A', 486),
('USHEC', 'Upper solu Electric company Limited', 'Hydro Power', 'Equity', 'A', 487),
('NMBUR93/94', 'NMB Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 488),
('GIBF1', 'Global IME Balanced Fund-1', 'Mutual Fund', 'Mutual Funds', 'A', 489),
('RHGCL', 'Rapti Hydro and General Construction Limited', 'Hydro Power', 'Equity', 'A', 490),
('SBD89', 'Sanima Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 491),
('SBID83', 'Nepal SBI Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 492),
('PBD84', 'Prime Commercial Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 493),
('AVYAN', 'Aviyan laghubittya bittiya sanstha limited', 'Microfinance', 'Equity', 'A', 494),
('EBLD85', 'Everest Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 495),
('SPHL', 'Sayapatri Hydropower Limited', 'Hydro Power', 'Equity', 'A', 496),
('PPL', 'Peoples Power Limited', 'Hydro Power', 'Equity', 'A', 497),
('DLBS', 'Dhaulagiri laghubitta Sanstha Limited', 'Microfinance', 'Equity', 'A', 498),
('NSIF2', 'NMB Capital Ltd.', 'Mutual Fund', 'Mutual Funds', 'A', 499),
('SIKLES', 'Sikles Hydropower Limited', 'Hydro Power', 'Equity', 'A', 500),
('KBLD89', 'Kumari Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 501),
('KLBS', 'Khaptad Laghubitta Bittiya Sanstha Ltd', 'Microfinance', 'Equity', 'D', 502),
('EHPL', 'Eastern Hydropower Limited', 'Hydro Power', 'Equity', 'A', 503),
('SHLB', 'Shrijanshil Laghubitta Baittiya sanstha Limited', 'Microfinance', 'Equity', 'A', 504),
('PHCL', 'Peoples Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 505),
('BHPL', 'Barahi Hydropower Public Limited', 'Hydro Power', 'Equity', 'A', 506),
('BOKD86KA', 'Bank of Kathmandu Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 507),
('HBLD86', 'Himalayan Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 508),
('NIBLGF', 'NIBL Growth Fund', 'Mutual Fund', 'Mutual Funds', 'A', 509),
('SAGF', 'Sanima Growth Fund', 'Mutual Fund', 'Mutual Funds', 'A', 510),
('UNLB', 'Unique Nepal Laghubitta Bittiya Sanstha Limited', 'Microfinance', 'Equity', 'A', 511),
('NIFRAUR85/86', 'Nepal Infrastructure Bank Limited', 'Investment', 'Non-Convertible Debentures', 'A', 512),
('SMHL', 'Super Madi Hydropower Limited', 'Hydro Power', 'Equity', 'A', 513),
('SPL', 'SHUVAM POWER LIMITED', 'Hydro Power', 'Equity', 'A', 514),
('SMH', 'Supermai Hydropower Limited', 'Hydro Power', 'Equity', 'A', 515),
('MKHC', 'Maya Khola Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 516),
('AHL', 'Asian Hydropower Limited', 'Hydro Power', 'Equity', 'A', 517),
('KDL', 'KALINCHOWK DARSHAN LIMITED ', 'Hotels And Tourism', 'Equity', 'A', 518),
('EBLEB89', 'Everest Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 519),
('SFEF', 'Sunrise Capital Limited', 'Commercial Banks', 'Mutual Funds', 'A', 520),
('TAMOR', 'Sanima Middle Tamor Hydropower Limited', 'Hydro Power', 'Equity', 'A', 521),
('MHCL', 'Molung Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 522),
('SMJC', 'Sagarmatha Jalabidhyut Company Limited', 'Hydro Power', 'Equity', 'A', 523),
('ANLB', 'Aatmanirbhar Laghubitta Bittitya Sanstha Limited', 'Microfinance', 'Equity', 'A', 524),
('BPW', 'BPW Laghubitta Bittiya Sanstha', 'Microfinance', 'Equity', 'D', 525),
('MAKAR', 'Makar Jitumaya Suri Hydropower Ltd ', 'Hydro Power', 'Equity', 'A', 526),
('MKHL', 'MaiKhola Hydropower Limited', 'Hydro Power', 'Equity', 'A', 527),
('GBILD84/85', 'Global IME Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 528),
('DOLTI', 'Dolti Power Company Ltd.', 'Hydro Power', 'Equity', 'A', 529),
('BEDC', 'Bhugol Energy Development Company Ltd', 'Hydro Power', 'Equity', 'A', 530),
('CITY', 'CITY HOTEL LIMITED ', 'Hotels And Tourism', 'Equity', 'A', 531),
('PRSF', 'Prabhu Capital Limited', 'Mutual Fund', 'Mutual Funds', 'A', 532),
('MCHL', 'Menchhiyam Hydro Power Ltd', 'Hydro Power', 'Equity', 'A', 533),
('IHL', 'Ingwa Hydropower Limited', 'Hydro Power', 'Equity', 'A', 534),
('SCBD', 'Standard Chartered Bank  Nepal Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 535),
('RMF2', 'RBB Merchant Banking Limited', 'Mutual Fund', 'Mutual Funds', 'A', 536),
('MEL', 'Modi Energy Limited', 'Hydro Power', 'Equity', 'A', 537),
('NMBD89/90', 'NMB Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 538),
('RAWA', 'Rawa Energy Development Ltd.', 'Hydro Power', 'Equity', 'A', 539),
('SIGS3', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 540),
('NRM', 'Nepal Republic Media Ltd', 'Others', 'Equity', 'A', 541),
('ILI', 'I.M.E. Life Insurance company Limited ', 'Life Insurance', 'Equity', 'A', 542),
('C30MF', 'Citizens Bank International Limited', 'Commercial Banks', 'Mutual Funds', 'A', 543),
('USHL', ' Upper Syange Hydropower Limited', 'Hydro Power', 'Equity', 'A', 544),
('GCIL', 'Ghorahi Cement Industry Limited', 'Manufacturing And Processing', 'Equity', 'A', 545),
('TSHL', 'Three Star Hydropower Ltd', 'Hydro Power', 'Equity', 'A', 546),
('MLBLD89', 'Mahalaxmi Bikas Bank Ltd.', 'Development Banks', 'Non-Convertible Debentures', 'A', 547),
('KBSH', 'Kutheli Bukhari Small Hydropower Ltd', 'Hydro Power', 'Equity', 'A', 548),
('LBBLD89', 'Lumbini Bikas Bank Ltd.', 'Development Banks', 'Non-Convertible Debentures', 'A', 549),
('LVF2', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 550),
('RNLI', 'Reliable Nepal Life Insurance Ltd', 'Life Insurance', 'Equity', 'A', 551),
('SNLI', 'Sun Nepal Life Insurance Company Limited', 'Life Insurance', 'Equity', 'A', 552),
('MEHL', 'Manakamana Engineering Hydropower Limited', 'Hydro Power', 'Equity', 'A', 553),
('ULHC', 'Upper Lohore Khola Hydropower Company Limited', 'Hydro Power', 'Equity', 'A', 554),
('CLI', 'Citizen Life Insurance Company Limited', 'Life Insurance', 'Equity', 'A', 555),
('SBID89', 'Nepal SBI Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 556),
('MANDU', 'Mandu Hydropower Limited', 'Hydro Power', 'Equity', 'A', 557),
('HATHY', 'HATHWAY INVESTMENT NEPAL LIMITED', 'Investment', 'Equity', 'A', 558),
('BGWT', 'Bhagawati Hyropower Development Company Ltd.', 'Hydro Power', 'Equity', 'A', 559),
('MSHL', 'Mid solu Hydropower Limited', 'Hydro Power', 'Equity', 'A', 560),
('SONA', 'Sonapur Minerals And Oil Limited', 'Manufacturing And Processing', 'Equity', 'A', 561),
('MMKJL', 'Mathillo Mailun Khola Jalvidhyut Ltd.', 'Hydro Power', 'Equity', 'A', 562),
('TVCL', 'Trishuli Jal Vidhyut Company Limited ', 'Hydro Power', 'Equity', 'A', 563),
('KBLD90', 'Kumari Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 564),
('H8020', 'Himalayan Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 565),
('VLUCL', 'Vision Lumbini Urja Company Limited', 'Hydro Power', 'Equity', 'A', 566),
('MKCL', 'Muktinath Krishi Company Limited', 'Others', 'Equity', 'A', 567),
('CIZBD90', 'Citizens Bank International Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 568),
('CKHL', 'Chirkhwa Hydropower Limited', 'Hydro Power', 'Equity', 'A', 569),
('NWCL', 'Nepal Warehousing Company Limited', 'Others', 'Equity', 'A', 570),
('HRL', 'Himalayan Reinsurance Limited', 'Others', 'Equity', 'A', 571),
('NICGF2', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Mutual Funds', 'A', 572),
('NABILD87', 'Nabil Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 573),
('KSY', 'Kumari Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 574),
('SARBTM', 'Sarbottam Cement Limited', 'Manufacturing And Processing', 'Equity', 'A', 575),
('NIMBD90', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 576),
('NIBLSTF', 'Nepal Investment Mega Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 577),
('MNMF1', 'Muktinath Bikas Bank Ltd.', 'Development Banks', 'Mutual Funds', 'A', 578),
('GMLI', 'GUARDIAN MICRO LIFE INSURANCE LIMITED', 'Life Insurance', 'Equity', 'A', 579),
('GSY', 'Garima Bikas Bank Limited', 'Development Banks', 'Mutual Funds', 'A', 580),
('ICFCD88', 'ICFC Finance Limited', 'Finance', 'Non-Convertible Debentures', 'A', 581),
('NMIC', 'Nepal Micro Insurance Company Limited', 'Non Life Insurance', 'Equity', 'A', 582),
('CREST', 'Crest Micro Life Insurance Limited', 'Life Insurance', 'Equity', 'A', 583),
('NMBHF2', 'NMB Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 584),
('EBLD91', 'Everest Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 585),
('OMPL', 'Om Megashree Pharmaceuticals Limited', 'Manufacturing And Processing', 'Equity', 'A', 586),
('MBLEF', 'Machhapuchhre Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 587),
('PURE', 'Pure Energy Limited', 'Others', 'Equity', 'A', 588),
('RSY', 'Reliable Nepal Life Insurance Ltd', 'Life Insurance', 'Mutual Funds', 'A', 589),
('NIFRAGED', 'Nepal Infrastructure Bank Limited', 'Investment', 'Non-Convertible Debentures', 'A', 590),
('TTL', 'Trade Tower Limited', 'Others', 'Equity', 'A', 591),
('SANVI', 'Sanvi Energy Limited', 'Hydro Power', 'Equity', 'A', 592),
('RBBD2088', 'Rastriya Banijya Bank', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 593),
('NICAD2091', 'NIC Asia Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 594),
('BHCL', 'Bikash Hydropower Company Ltd', 'Hydro Power', 'Equity', 'A', 595),
('GBIMESY2', 'Global IME Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 596),
('HIMSTAR', 'Himstar Urja Company Ltd.', 'Hydro Power', 'Equity', 'A', 597),
('SBLD2091', 'Siddhartha Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 598),
('SHINED', 'SHINE RESUNGA DEVELOPMENT BANK LTD', 'Development Banks', 'Non-Convertible Debentures', 'A', 599),
('MABEL', 'Mabilung Energy Limited', 'Hydro Power', 'Equity', 'A', 600),
('SBID2090', 'Nepal SBI Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 601),
('HLICF', 'Himalayan Life Insurance Limited', 'Life Insurance', 'Mutual Funds', 'A', 602),
('DHEL', 'Daramkhola hydro Energy Ltd.', 'Hydro Power', 'Equity', 'A', 603),
('SAGAR', 'Sagar Distillery Limited', 'Manufacturing And Processing', 'Equity', 'A', 604),
('SWASTIK', 'SWASTIK LAGHUBITTA BITTIYA SANSTHA LTD.', 'Microfinance', 'Equity', 'A', 605),
('BUNGAL', 'Bungal Hydro Limited', 'Hydro Power', 'Equity', 'A', 606),
('BANDIPUR', 'Bandipur Cable Car and Tourism Limited', 'Hotels And Tourism', 'Equity', 'A', 607),
('NABILD2089', 'Nabil Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 608),
('JHAPA', 'Jhapa Energy Limited', 'Others', 'Equity', 'A', 609),
('SAIL', 'SHREENAGAR AGRITECH INDUSTRIES LIMITED', 'Manufacturing And Processing', 'Equity', 'A', 610),
('RBBF40', 'RBB Merchant Banking Limited', 'Mutual Fund', 'Mutual Funds', 'A', 611),
('SYPNL', 'SY PANEL NEPAL LIMITED', 'Manufacturing And Processing', 'Equity', 'A', 612),
('CSY', 'Citizens Bank International Limited', 'Commercial Banks', 'Mutual Funds', 'A', 613),
('SABBL', 'Salapa Bikas Bank Limited', 'Development Banks', 'Equity', 'A', 614),
('RSML', 'Reliance Spinning Mills Limited', 'Manufacturing And Processing', 'Equity', 'A', 615),
('HFIN', 'Hotel Forest Inn Limited', 'Hotels And Tourism', 'Equity', 'A', 616),
('SOHL', 'Solu Hydropower Limited', 'Hydro Power', 'Equity', 'A', 617),
('NSY', 'NEPAL LIFE INSURANCE COMPANY LIMITED', 'Life Insurance', 'Mutual Funds', 'A', 618),
('BJHL', 'Bhujung Hydropower Limited', 'Hydro Power', 'Equity', 'A', 619),
('SKHL', 'Super Khudi Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 620),
('RLEL', 'RIDGE LINE ENERGY LIMITED', 'Hydro Power', 'Equity', 'A', 621),
('SKHEL', 'Suryakunda Hydro Electric Limited', 'Hydro Power', 'Equity', 'A', 622),
('NABILPNP', 'Nabil Bank Limited', 'Commercial Banks', 'Preference Shares', 'A', 623),
('ICFCD89', 'ICFC Finance Limited', 'Finance', 'Non-Convertible Debentures', 'A', 624),
('KSBBLPNP', 'Kamana Sewa Bikas Bank Limited', 'Development Banks', 'Preference Shares', 'A', 625),
('SIPD', 'Shikhar Power Development Ltd.', 'Hydro Power', 'Equity', 'A', 626),
('PCIL', 'Palpa Cement Industries Limited', 'Manufacturing And Processing', 'Equity', 'A', 627),
('SBLPNP', 'Siddhartha Bank Limited', 'Commercial Banks', 'Preference Shares', 'A', 628),
('NMBPNP', 'NMB Bank Limited', 'Commercial Banks', 'Preference Shares', 'A', 629),
('SANIMAPNP', 'Sanima Bank Limited', 'Commercial Banks', 'Preference Shares', 'A', 630),
('KHPL', 'Kalinchock Hydropower Limited', 'Hydro Power', 'Equity', 'A', 631),
('MBLPNP', 'Machhapuchhre Bank Limited', 'Commercial Banks', 'Preference Shares', 'A', 632),
('SOPL', 'Sopan Pharmaceuticals Limited', 'Manufacturing And Processing', 'Equity', 'A', 633),
('APHL', 'Appolo Hydropower Limited', 'Hydro Power', 'Equity', 'A', 634),
('YMHL', 'Yambaling Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 635),
('TPKHL', 'Taksar Pikhuwa Khola Hydropower Ltd.', 'Hydro Power', 'Equity', 'A', 636),
('SNORL', 'Snow Rivers Limited', 'Hydro Power', 'Equity', 'A', 637),
('SGHL', 'Sanigad Hydro Limited', 'Hydro Power', 'Equity', 'A', 638),
('KAHL', 'Kalanga Hydro Limited', 'Hydro Power', 'Equity', 'A', 639),
('ECL', 'Everest Colour Ltd.', 'Manufacturing And Processing', 'Equity', 'A', 640),
('SEF2', 'Siddhartha Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 641),
('SAEF2', 'Sanima Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 642),
('LSH12', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Mutual Funds', 'A', 643),
('RSY2', 'Reliable Nepal Life Insurance Ltd', 'Life Insurance', 'Mutual Funds', 'A', 644),
('MEPDL', 'Mount Everest Power Development Limited', 'Hydro Power', 'Equity', 'A', 645),
('SAPIL', 'SARVOTTAM PAINTS INDUSTRIES LTD.', 'Manufacturing And Processing', 'Equity', 'A', 646),
('PBD93', 'Prime Commercial Bank Ltd.', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 647),
('LSD92', 'Laxmi Sunrise Bank Limited', 'Commercial Banks', 'Non-Convertible Debentures', 'A', 648)
on conflict (symbol) do update set company_name = excluded.company_name, sector_name = excluded.sector_name, instrument_type = excluded.instrument_type, status = excluded.status, sort_order = excluded.sort_order;
